christopherwk210/gm-bot

src/rules.ts
Added !jobsheet / !jobboard which replies with a basic message and a link to the job sheet.
=> !jobsheet / !jobboard

src/rules.ts
Updated !jobsheet / !jobboard to include information about contacting a staff member to be added to the list.
=> Update to !jobsheet for insturctions

gmbot.ts, src/commands/index.ts, src/commands/security/security.command.ts, src/rules.ts, src/shared/index.ts, src/shared/services/security.service.ts
=> Created Security Command

src/commands/security/security.command.ts
Look bubsy, all I'm saying is a read book on fuckin design, all I'm saying, first like is "fuckin topher's wrong" that's what that first line says
--- <3
=> CHANGING OPTIONAL ARGUMENTS BECAUSE YOU LACK DECENCY

src/commands/done/done.command.ts, src/shared/services/help-channel.service.ts
Makes changes to the !done command and help channel service by allowing not only higher level users to use the !done command but also the user who originally made the channel busy in the first place
=> !done usage for whoever made the channel busy

src/commands/done/done.command.ts, src/shared/services/help-channel.service.ts
so users can't busy/unbusy channels like ANIMALS
=> Added '!done' check to messages sent by non-staff

package-lock.json, package.json, src/commands/docs/docs.command.ts, src/shared/services/doc.service.ts
Adds new behaviour to when !doc command fails to find an exact match: it returns 5 closest matches according to Dice's Coefficient (from the npm [string-similarity](https://www.npmjs.com/package/string-similarity) package).
=> Adds "did you mean...?" when !doc command doesn't find an exact match

src/shared/services/doc.service.ts
Sara is a dingus. She removed the log command but not the stupid message.
=> Actually removes the message

src/commands/role-control/role-control.command.ts, src/config.ts
=> fixed !3d and !shader

src/config.ts, src/shared/services/doc.service.ts
Removed white spaces from config.ts as well. BAD MES
=> Fantastic code, such impressive try/catch

src/config.ts, src/shared/services/help-channel.service.ts
lmao jk. In this commit I added a quick modification that changes the topic of the help channels when they're busy, to alert everyone as to who is asking for help
=> The coolest commit you'll ever see

src/commands/done/done.command.ts
=> Extremely important update for Halloween

src/commands/starter/starter.command.ts
Added a link that yosi wanted me to add, its about 3d stuff. Also fixed a bunch of typos because i cant spell ):
=> Im sorry guys I cant spel good.

src/commands/done/done.command.ts
lazyeye it's one line of code
not even code
=> no more halloween

docs/features/commands/done.md, src/commands/done/done.command.ts
praise be to the peasant folk!
bring forth the inquiry!
=> hey look i made it so people wont complain about the !done command!

src/commands/starter/resources.ts
Added link to a mini article about making a platformer.
=> Added new link.

gmbot.ts, package-lock.json, src/shared/index.ts, src/shared/utils/spambot.ts
God I hope I got this right. Added automatic spambot detection, works with the spambots that have recently hit the server. Can be extended to handle other spambots as well.
=> Added spambot detection to GMBot

src/shared/utils/spambot.ts
Case insensitive detection, added 18+ keyword. Suggestions welcome
=> Updated spambot detection

src/modifiers/haste/haste.modifier.ts
I'm updating some stuff relating to firebin's hosting, so will need to update the endpoint
=> Updating the firebin endpoint

package-lock.json, src/commands/palette/palette.command.ts
The !palette command can use the bot's admin permissions to ping @ everyone and @ here. This adds a space after every @ in the printed result (which honestly wouldn't appear in most palette names anyway) to prevent this.
=> Sanitising input from !palette

gmbot.ts, src/config.ts, src/shared/assets/json/auth.example.json, src/shared/index.ts, src/shared/services/voice-channel.service.ts
The bot will now delete messages from users who send a message into a voice text channel without being present in the relevant voip channel. The bot will auto delete _all_ messages in voice text channels 3 hours after they were sent.
=> Add Voice Channel Service Functionality

src/commands/vote/vote.command.ts, src/config.ts
=> Fixing !vote-wiz for cats

package-lock.json, src/rules.ts, src/shared/services/react-role-distribution.service.ts
Also fixed some whitespace in the rules.ts file because it wasn't passing the lint rules
=> Modify role assignment feature, roles now appear in order. 
